/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/Dave.glb -Tt
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Dave-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 1, 2.5]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/Dave-transformed.glb')
